version: "2"
services:
  doclever:
    image: registry-vpc.cn-beijing.aliyuncs.com/wzx/doclever:5.0.1
    restart: always
    container_name: "api"
    ports:
      - "10000:10000"
    volumes:
      - /data1/DOClever/file:/root/DOClever/data/file
      - /data1/DOClever/img:/root/DOClever/data/img
      - /data1/DOClever/tmp:/root/DOClever/data/tmp
      - /data/lnmp/www/:/www/:rw
    environment:
      - DB_HOST=mongodb://mongo:27017/DOClever
      - PORT=10000
      - DB_FILE=/root/DOClever/data/file
      - DB_IMG=/root/DOClever/data/img
      - DB_TEMP=/root/DOClever/data/tmp
    links:
      - mongo:mongo

  mongo:
    image: registry.cn-beijing.aliyuncs.com/wzx/mongo:3.0.15
    restart: always
    container_name: "mongo"
    volumes:
      - /data1/mongo_data:/data/db
